### PR TITLE
support short name for method and parameter with isRequired

### PR DESCRIPTION
**Pull request by yishengjin1413**

### CODE REVIEW

**Comment by joelmartinez** [comment]
@yishengjin1413 this change looks just fine ... you should just re-open this PR as I don't really have any other items to add to it :)

**Review by joelmartinez — CHANGES_REQUESTED** [review]
Oh, we need to bump the version number :)

**Comment by yishengjin1413** [comment]
@joelmartinez Good catch~

**Review by joelmartinez — APPROVED** [review]
Thanks!

**Pull request merged**
